# Form implementation generated from reading ui file '.\youtube_downloader.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from os.path import expanduser, join
from PyQt6 import QtCore, QtWidgets, QtGui
import pytube_features


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.download_path = self.userDownloadPath()

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 280)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # icon更換
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\img\\yt.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)

        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 53, 16))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 53, 16))
        self.label_2.setObjectName("label_2")

        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 50, 341, 21))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 80, 251, 21))
        self.lineEdit_2.setText(self.userDownloadPath())
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 130, 75, 24))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 130, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(370, 80, 75, 24))
        self.pushButton_3.setObjectName("pushButton_3")

        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(110, 180, 330, 23))
        self.progressBar.setFormat('%p%')
        self.progressBar.setRange(0, 100)
        self.progressBar.setValue(0)
        self.progressBar.setObjectName("progressBar")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 523, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        # bind按鈕事件
        self.pushButton.clicked.connect(self.downloadVideo)
        self.pushButton_2.clicked.connect(self.downloadAudio)
        self.pushButton_3.clicked.connect(self.selectDownloadPath)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube Downloader"))
        self.pushButton.setText(_translate("MainWindow", "下載影片"))
        self.pushButton_2.setText(_translate("MainWindow", "下載音訊"))
        self.label.setText(_translate("MainWindow", "URL"))
        self.label_2.setText(_translate("MainWindow", "下載至"))
        self.pushButton_3.setText(_translate("MainWindow", "選擇資料夾"))

    def downloadVideo(self):
        '''
        下載影片
        '''
        self.youtube_url = self.lineEdit.text()
        pyt = pytube_features.PytubeDownload(self.youtube_url, self.download_path, self.progressBar)
        pyt.downloadVideo()

    def downloadAudio(self):
        '''
        下載MP3
        '''
        self.youtube_url = self.lineEdit.text()
        pyt = pytube_features.PytubeDownload(self.youtube_url, self.download_path, self.progressBar)
        pyt.downloadAudio()

    def userDownloadPath(self):
        '''
        取得User下的下載資料夾位置
        '''
        homePath = expanduser("~")
        downloadPath = join(homePath, 'Downloads')
        return downloadPath

    def selectDownloadPath(self):
        '''
        選擇下載資料夾路徑
        '''
        filePath = QtWidgets.QFileDialog.getExistingDirectory()  # 選擇檔案對話視窗
        self.lineEdit_2.setText(filePath)
        self.download_path = filePath